apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-monitoring
spec:
  version: 7.14.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
---